# This Dockerfile will build an image with simple decord with no gpu support and objective-metrics package.
# Due to nvidia/cuda base image, cuda and nvidia drivers from host machine will be mounted inside a running container.
# So, you need to have preinstalled cuda and nvidia-container-toolkit on the host.
# See nvidia/cuda docs (https://hub.docker.com/r/nvidia/cuda).

FROM nvidia/cuda:12.0.1-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow

RUN apt-get update && apt-get -y install gcc git cmake ffmpeg python3 python3-pip

# Timezone Moscow
RUN apt-get -y install tzdata
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install Ffmpeg static build with libvmaf (https://johnvansickle.com/ffmpeg/)
RUN apt-get -y install wget xz-utils
RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
RUN tar xvf ffmpeg-git-amd64-static.tar.xz
RUN cp -r ffmpeg-git-*-amd64-static/model /usr/local/share/
RUN mv ffmpeg-git-*-amd64-static/ffmpeg ffmpeg-git-*-amd64-static/ffprobe /usr/local/bin/

# Install Decord
RUN pip3 install decord

# Install objective-metrics package
RUN pip install objective-metrics

# Make a storage
WORKDIR /app

ENTRYPOINT ["objective_metrics_run"]
